# Generated by Django 5.1.1 on 2024-09-20 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('nucleo', '0002_initial'),
        ('ordendecompra', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialbodegainsumo',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.insumo', verbose_name='Insumo'),
        ),
        migrations.AddField(
            model_name='historialbodegaproducto',
            name='historialbodega',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.historialbodega', verbose_name='Bodega'),
        ),
        migrations.AddField(
            model_name='historialbodegaproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='insumobulto',
            name='bodega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.bodega', verbose_name='bodega'),
        ),
        migrations.AddField(
            model_name='insumobulto',
            name='insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.insumo', verbose_name='Insumo'),
        ),
        migrations.AddField(
            model_name='insumobulto',
            name='ordendecompra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordendecompra.ordendecompra', verbose_name='Orden de compra asociada'),
        ),
        migrations.AddField(
            model_name='insumobultohijo',
            name='insumobultohijo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hijo', to='inventario.insumobulto', verbose_name='Bulto Hijo'),
        ),
        migrations.AddField(
            model_name='insumobultohijo',
            name='insumobultopadre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padre', to='inventario.insumobulto', verbose_name='Bulto Padre'),
        ),
        migrations.AddField(
            model_name='inventarioinsumo',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.bodega', verbose_name='bodega'),
        ),
        migrations.AddField(
            model_name='inventarioinsumo',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.insumo', verbose_name='Insumo'),
        ),
        migrations.AddField(
            model_name='inventarioproducto',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.bodega', verbose_name='bodega'),
        ),
        migrations.AddField(
            model_name='inventarioproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='supervisorbodega',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.bodega', verbose_name='Bodega'),
        ),
        migrations.AddField(
            model_name='supervisorbodega',
            name='supervisor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Supervisor de Planta'),
        ),
        migrations.AlterUniqueTogether(
            name='inventarioinsumo',
            unique_together={('bodega', 'insumo')},
        ),
        migrations.AlterUniqueTogether(
            name='inventarioproducto',
            unique_together={('bodega', 'producto')},
        ),
    ]
