# Generated by Django 5.1.1 on 2024-09-20 15:35

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrdenDeCompra',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('pagada', models.BooleanField(default=False, help_text='Si la orden de compra ha sido pagada.', verbose_name='Pagada')),
                ('numero', models.BigIntegerField(db_index=True, verbose_name='Numero')),
                ('condiciones', models.TextField(blank=True, default='Por favor incluir la siguiente glosa en la factura: DESARROLLO DE PORTAFOLIO DE POSTRES VEGETALES A BASE DE ALMENDRA Y DESECHOS DE SU PRODUCCIÓN”, código 19IR-LR-121872', null=True, verbose_name='Condiciones')),
                ('estado', models.CharField(choices=[('Inicial', 'Inicial'), ('Validada', 'Validada'), ('Semi-Recepcionada', 'Semi-Recepcionada'), ('Recepcionada', 'Recepcionada'), ('Etiquetada', 'Etiquetada'), ('Pagada', 'Pagada')], max_length=50, verbose_name='Estado')),
                ('fecha', models.DateField(verbose_name='Fecha de emisión')),
                ('total_neto', models.FloatField(default=0, verbose_name='Total Neto')),
                ('guia_despacho', models.CharField(blank=True, max_length=50, null=True, verbose_name='Guia de despacho')),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de factura')),
                ('fecha_recepcion', models.DateField(blank=True, null=True, verbose_name='Fecha de recepción')),
                ('fecha_facturacion', models.DateField(blank=True, null=True, verbose_name='Fecha de documento')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('pago', models.CharField(blank=True, choices=[('cheque', 'Cheque'), ('deposito bancario', 'Depósito Bancario'), ('transferencia', 'Transferencia Electrónica'), ('efectivo', 'Efectivo'), ('otra', 'Otra')], max_length=100, null=True, verbose_name='Forma de pago')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bodega', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.bodega', verbose_name='Lugar')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proveedores.proveedor', verbose_name='Proovedor')),
            ],
            options={
                'verbose_name': 'historical Orden de compra',
                'verbose_name_plural': 'historical Ordenes de compra',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OrdenDeCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagada', models.BooleanField(default=False, help_text='Si la orden de compra ha sido pagada.', verbose_name='Pagada')),
                ('numero', models.BigIntegerField(unique=True, verbose_name='Numero')),
                ('condiciones', models.TextField(blank=True, default='Por favor incluir la siguiente glosa en la factura: DESARROLLO DE PORTAFOLIO DE POSTRES VEGETALES A BASE DE ALMENDRA Y DESECHOS DE SU PRODUCCIÓN”, código 19IR-LR-121872', null=True, verbose_name='Condiciones')),
                ('estado', models.CharField(choices=[('Inicial', 'Inicial'), ('Validada', 'Validada'), ('Semi-Recepcionada', 'Semi-Recepcionada'), ('Recepcionada', 'Recepcionada'), ('Etiquetada', 'Etiquetada'), ('Pagada', 'Pagada')], max_length=50, verbose_name='Estado')),
                ('fecha', models.DateField(verbose_name='Fecha de emisión')),
                ('total_neto', models.FloatField(default=0, verbose_name='Total Neto')),
                ('guia_despacho', models.CharField(blank=True, max_length=50, null=True, verbose_name='Guia de despacho')),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de factura')),
                ('fecha_recepcion', models.DateField(blank=True, null=True, verbose_name='Fecha de recepción')),
                ('fecha_facturacion', models.DateField(blank=True, null=True, verbose_name='Fecha de documento')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('pago', models.CharField(blank=True, choices=[('cheque', 'Cheque'), ('deposito bancario', 'Depósito Bancario'), ('transferencia', 'Transferencia Electrónica'), ('efectivo', 'Efectivo'), ('otra', 'Otra')], max_length=100, null=True, verbose_name='Forma de pago')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.bodega', verbose_name='Lugar')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedor', to='proveedores.proveedor', verbose_name='Proovedor')),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Ordenes de compra',
                'ordering': ['numero'],
                'permissions': (('listar', 'Puede ver las ordenes de compra'), ('crear', 'Puede crear una orden de compra'), ('pdf', 'Permite generar el pdf de una orden de compra'), ('recepcionar', 'Permite recepcionar una orden de compra'), ('rechazar', 'Permite rechazar una orden de compra'), ('validar', 'Permite validar una orden de compra'), ('eliminar', 'Permite eliminar una orden de compra'), ('pagar', 'Permite pagar una orden'), ('eliminararchivo', 'Permite eliminar archivos asociados a las ordenes de compra'), ('verarchivo', 'Permite ver los archivos adjuntos'), ('dividir', 'Permite dividir un bulto de insumos')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='HistoricalOrdenDeCompraInsumo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cantidad', models.BigIntegerField(verbose_name='Cantidad')),
                ('cantidad_recibida', models.BigIntegerField(default=0, verbose_name='Cantidad Recibida')),
                ('neto', models.FloatField(verbose_name='Valor Neto')),
                ('moneda', models.FloatField(default=0, verbose_name='Moneda')),
                ('conversion', models.FloatField(blank=True, null=True, verbose_name='Conversion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('insumo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proveedores.proveedorinsumo', verbose_name='Insumo')),
                ('orden', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ordendecompra.ordendecompra', verbose_name='Orden de compra')),
            ],
            options={
                'verbose_name': 'historical orden de compra insumo',
                'verbose_name_plural': 'historical orden de compra insumos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='ordendecompra/adjuntos', verbose_name='Archivos Adjuntos')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordendecompra.ordendecompra', verbose_name='Orden de compra')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OrdenDeCompraInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.BigIntegerField(verbose_name='Cantidad')),
                ('cantidad_recibida', models.BigIntegerField(default=0, verbose_name='Cantidad Recibida')),
                ('neto', models.FloatField(verbose_name='Valor Neto')),
                ('moneda', models.FloatField(default=0, verbose_name='Moneda')),
                ('conversion', models.FloatField(blank=True, null=True, verbose_name='Conversion')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedorinsumo', verbose_name='Insumo')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordendecompra.ordendecompra', verbose_name='Orden de compra')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='insumos',
            field=models.ManyToManyField(through='ordendecompra.OrdenDeCompraInsumo', to='proveedores.proveedorinsumo', verbose_name='Insumos'),
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=255, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='empleado', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordendecompra.ordendecompra', verbose_name='Orden de compra')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'default_permissions': (),
            },
        ),
    ]
