# Generated by Django 5.1.1 on 2024-09-20 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre Área')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('lugar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.bodega')),
            ],
            options={
                'verbose_name': 'área',
                'verbose_name_plural': 'áreas',
                'permissions': (('area.listar', 'Puede ver las areas'), ('area.crear', 'Puede añadir un area'), ('area.eliminar', 'Puede eliminar una area'), ('area.actualizar', 'Puede actualizar un area')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre Equipo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipo.areaequipo')),
            ],
            options={
                'verbose_name': 'equipo',
                'verbose_name_plural': 'equipos',
                'permissions': (('listar', 'Puede ver los equipos'), ('crear', 'Puede añadir un equipo'), ('eliminar', 'Puede eliminar un equipo'), ('actualizar', 'Puede actualizar un equipo'), ('qrlimpieza', 'Permite generar el qr de limpieza')),
                'default_permissions': (),
            },
        ),
    ]
