# Generated by Django 5.1.1 on 2024-09-20 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Linea')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'linea de producto',
                'verbose_name_plural': 'lineas de producto',
                'ordering': ['nombre'],
                'permissions': (('linea.listar', 'Puede ver las lineas de negocio'), ('linea.crear', 'Puede crear una linea de negocio'), ('linea.eliminar', 'Puede eliminar un linea de negocio'), ('linea.actualizar', 'Puede actualizar una linea de negocio')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre Moneda')),
                ('valor', models.FloatField(verbose_name='Valor Moneda')),
                ('fecha', models.CharField(max_length=255, verbose_name='Fecha de extraccion')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['-id'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Permiso')),
            ],
            options={
                'permissions': (('permiso.crear.usuario', 'Permite Crear Usuarios'), ('permiso.actualizar.usuario', 'Permite Actualizar Usuarios'), ('permiso.eliminar.usuario', 'Permite Eliminar Usuarios'), ('permiso.listar.usuario', 'Permite Listar Usuarios')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Rama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre del área de negocio')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'rama',
                'verbose_name_plural': 'ramas',
                'ordering': ['nombre'],
                'permissions': (('rama.listar', 'Puede ver las áreas de negocio'), ('rama.crear', 'Puede crear una área de negocio'), ('rama.eliminar', 'Puede eliminar un área de negocio'), ('rama.actualizar', 'Puede actualizar un área de negocio')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre genérico del insumo')),
                ('unidad', models.CharField(choices=[('', '---------'), ('N/A', 'N/A'), ('Unidad', 'Unidades'), ('Caja', 'Cajas'), ('Kilogramo', 'Kilogramos'), ('Litro', 'Litros')], max_length=50, verbose_name='Unidad de medida')),
                ('stock_critico', models.FloatField(verbose_name='Stock Crítico')),
                ('pip', models.BooleanField(default=False, verbose_name='Si es un insumo que se genera al interior de la empresa.')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'insumo',
                'verbose_name_plural': 'insumos',
                'ordering': ['-created'],
                'permissions': (('insumo.listar', 'Puede listar los insumos'), ('insumo.crear', 'Puede crear un insumo'), ('insumo.eliminar', 'Puede eliminar un insumo'), ('insumo.actualizar', 'Puede actualizar un insumo')),
                'default_permissions': (),
                'unique_together': {('nombre', 'unidad')},
            },
        ),
        migrations.CreateModel(
            name='InsumoDirectoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('porcentaje_uso', models.FloatField(default=0, verbose_name='Porcentaje uso')),
                ('detalle', models.CharField(max_length=255, verbose_name='Detalle del insumo directo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.insumo', verbose_name='Insumo')),
            ],
            options={
                'verbose_name': 'insumo directo de producción',
                'verbose_name_plural': 'insumos directos de producción',
                'ordering': ['producto__nombre'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InsumoElaboracionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(verbose_name='cantidad por kilo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.insumo', verbose_name='Insumo')),
            ],
            options={
                'verbose_name': 'insumo producto',
                'verbose_name_plural': 'insumos producto',
                'ordering': ['insumo__nombre'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='El nombre que poseera el producto.', max_length=255, verbose_name='Nombre del producto')),
                ('codigo', models.CharField(max_length=255, verbose_name='Código del producto')),
                ('descripcion', models.TextField(blank=True, default='', help_text='Descripción del producto para ficha técnica.', verbose_name='Descripción del producto')),
                ('presentacion', models.BigIntegerField(help_text='El peso o volumen del producto', verbose_name='Presentación')),
                ('unidad', models.CharField(choices=[('', '---------'), ('gr', 'gramos'), ('kg', 'kilogramos'), ('lt', 'litros'), ('cc', 'centimetros cúbico')], help_text='La unidad de medida del producto.', max_length=50, verbose_name='Unidad')),
                ('duracion', models.IntegerField(help_text='La vida util del producto luego de ser elaborado.', verbose_name='Vida útil del producto')),
                ('maduracion', models.BigIntegerField(help_text='La cantidad de días que el producto debe pasar en maduración.', verbose_name='Maduración')),
                ('stock_critico', models.BigIntegerField(help_text='La cantidad de stock minimo de este producto antes de levantar alertas.', verbose_name='Stock Crítico')),
                ('unidades', models.IntegerField(default=24, help_text='La cantidad de unidades por caja de este producto.', verbose_name='Unidades por caja')),
                ('dun14', models.CharField(blank=True, default='', help_text='El codigo DUN14 del producto.', max_length=14, verbose_name='DUN14')),
                ('id_comercio_net', models.CharField(blank=True, max_length=255, null=True, verbose_name='Identificador comercio electrónico')),
                ('sap', models.CharField(blank=True, default='', max_length=12, verbose_name='SAP')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('conjunto', models.ForeignKey(blank=True, default=None, help_text='Los procesos de valor agregado a los cuales debe someterse este producto.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estado.conjuntoestado', verbose_name='Estado')),
                ('descriptores', models.ManyToManyField(through='nucleo.InsumoDirectoProducto', to='nucleo.insumo', verbose_name='Descriptores')),
                ('linea', models.ForeignKey(default=None, help_text='La linea de negocio del producto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='nucleo.linea', verbose_name='Linea de negocio')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['id'],
                'permissions': (('producto.listar', 'Puede ver los productos'), ('producto.crear', 'Puede crear un producto'), ('producto.eliminar', 'Puede eliminar un producto'), ('producto.actualizar', 'Puede actualizar un producto')),
                'default_permissions': (),
            },
        ),
    ]
