# Generated by Django 5.1.1 on 2024-09-20 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0001_initial'),
        ('pauta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='pautalinea',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pautalinea', to='pauta.pauta', verbose_name='Pauta de Linea'),
        ),
        migrations.AddField(
            model_name='producto',
            name='pautapip',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pautapip', to='pauta.pauta', verbose_name='Pauta de elaboración PIP'),
        ),
        migrations.AddField(
            model_name='insumoelaboracionproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='insumodirectoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='linea',
            name='rama',
            field=models.ForeignKey(help_text='El área de negocio del producto.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.rama', verbose_name='Área de negocio'),
        ),
        migrations.AlterUniqueTogether(
            name='insumoelaboracionproducto',
            unique_together={('producto', 'insumo')},
        ),
        migrations.AlterUniqueTogether(
            name='insumodirectoproducto',
            unique_together={('producto', 'insumo')},
        ),
    ]
