# Generated by Django 5.1.1 on 2024-10-05 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lechero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del lechero')),
            ],
        ),
        migrations.AddField(
            model_name='insumo',
            name='lechero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.lechero', verbose_name='Lechero proveedor'),
        ),
    ]
