# Generated by Django 5.1.1 on 2024-10-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_remove_insumo_lechero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['id'], 'permissions': (('producto.listar', 'Puede ver los productos'), ('producto.crear', 'Puede crear un producto'), ('producto.eliminar', 'Puede eliminar un producto'), ('producto.actualizar', 'Puede actualizar un producto')), 'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
    ]
