# Generated by Django 5.1.1 on 2024-10-06 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_alter_producto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linea',
            options={'default_permissions': (), 'ordering': ['nombre'], 'permissions': (('linea.listar', 'Puede ver las líneas de negocio'), ('linea.crear', 'Puede crear una línea de negocio'), ('linea.eliminar', 'Puede eliminar una línea de negocio'), ('linea.actualizar', 'Puede actualizar una línea de negocio')), 'verbose_name': 'línea de producto', 'verbose_name_plural': 'líneas de producto'},
        ),
        migrations.AlterField(
            model_name='insumodirectoproducto',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='linea',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre de la Línea'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='rama',
            field=models.ForeignKey(help_text='El área de negocio del producto.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.rama', verbose_name='Área de Negocio'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
    ]
