# Generated by Django 5.1.1 on 2024-11-01 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0008_alter_insumoelaboracionproducto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linea',
            options={'default_permissions': (), 'ordering': ['nombre'], 'permissions': (('linea.listar', 'Puede ver las lineas de negocio'), ('linea.crear', 'Puede crear una linea de negocio'), ('linea.eliminar', 'Puede eliminar un linea de negocio'), ('linea.actualizar', 'Puede actualizar una linea de negocio')), 'verbose_name': 'linea de producto', 'verbose_name_plural': 'lineas de producto'},
        ),
        migrations.AlterField(
            model_name='linea',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre de la Linea'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='rama',
            field=models.ForeignKey(help_text='El área de negocio del producto.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.rama', verbose_name='Área de negocio'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='fecha',
            field=models.CharField(max_length=255, verbose_name='Fecha de extraccion'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre Moneda'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='valor',
            field=models.FloatField(verbose_name='Valor Moneda'),
        ),
        migrations.AlterField(
            model_name='rama',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre del área de negocio'),
        ),
    ]
