# Generated by Django 5.1.1 on 2024-11-10 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0009_alter_linea_options_alter_linea_created_and_more'),
        ('proveedores', '0003_alter_proveedor_empresa_rut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumodirectoproducto',
            name='precio_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedorinsumo'),
        ),
        migrations.CreateModel(
            name='CostoResumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_elaboracion_directo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_seco_directo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_costo_directo_unidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_costo_directo_kilogramo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.insumo', verbose_name='Insumo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Resumen de Costo',
                'verbose_name_plural': 'Resúmenes de Costos',
            },
        ),
    ]
