# Generated by Django 5.1.1 on 2024-11-11 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0010_alter_insumodirectoproducto_precio_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costoresumen',
            options={},
        ),
        migrations.RemoveField(
            model_name='costoresumen',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='costoresumen',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='costoresumen',
            name='costo_elaboracion_directo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.insumoelaboracionproducto', verbose_name='InsumoElaboracionProducto'),
        ),
        migrations.AlterField(
            model_name='costoresumen',
            name='costo_seco_directo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.insumodirectoproducto', verbose_name='InsumoDirectoProducto'),
        ),
    ]
