# Generated by Django 5.1.1 on 2024-11-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0011_alter_costoresumen_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumoelaboracionproducto',
            options={'default_permissions': (), 'ordering': ['insumo__nombre'], 'verbose_name': 'insumo producto', 'verbose_name_plural': 'insumos producto'},
        ),
        migrations.RemoveField(
            model_name='insumodirectoproducto',
            name='precio_proveedor',
        ),
        migrations.RemoveField(
            model_name='insumoelaboracionproducto',
            name='precio_provedor',
        ),
        migrations.AlterField(
            model_name='insumodirectoproducto',
            name='cantidad',
            field=models.IntegerField(verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='insumoelaboracionproducto',
            name='cantidad',
            field=models.FloatField(verbose_name='cantidad por kilo'),
        ),
        migrations.DeleteModel(
            name='CostoResumen',
        ),
    ]
