# Generated by Django 5.1.1 on 2024-09-20 15:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0001_initial'),
        ('nucleo', '0001_initial'),
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre de Lista de Precios')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Lista de Precios',
                'verbose_name_plural': 'Listas de Precios',
                'ordering': ['nombre'],
                'permissions': (('listap.listar', 'Puede ver el listado de los locales'), ('listap.crear', 'Puede crear un local'), ('listap.eliminar', 'Permite eliminar un local'), ('listap.actualizar', 'Permite actualizar un local'), ('listap.detalle', 'Permite ver el detalle de un local')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OrdenDeVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pickeado', 'Pickeado'), ('Facturado', 'Facturado'), ('Asignado', 'Asignado')], default='Pendiente', max_length=255)),
                ('complitud', models.FloatField(default=0, verbose_name='Nivel de servicio')),
                ('fecha', models.DateField(verbose_name='Fecha creación orden de Venta')),
                ('fecha_f', models.DateField(default=None, null=True, verbose_name='Fecha factura ov')),
                ('fecha_e', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de entrega')),
                ('condiciones', models.TextField(blank=True, null=True, verbose_name='Condiciones')),
                ('n_orden_cliente', models.CharField(blank=True, max_length=255, verbose_name='Número orden de compra cliente')),
                ('envio', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo de Envio')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente', verbose_name='Cliente')),
                ('entregado', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Encargado de Entrega')),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.clientelocal', verbose_name='Local')),
                ('lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.bodega', verbose_name='Lugar')),
            ],
            options={
                'verbose_name': 'Orden de Venta',
                'verbose_name_plural': 'Ordenes de Venta',
                'ordering': ['-pk'],
                'permissions': (('orden.listar', 'Puede ver el listado de las ordenes de venta'), ('orden.pickear', 'Permite realizar el pickeo de la orden'), ('orden.crear', 'Puede crear una orden de venta'), ('orden.abrir', 'Puede abrir cajas'), ('orden.retroceder', 'Puede retroceder la orden'), ('orden.excel', 'Puede exportar las ov en formato excel'), ('orden.entregar', 'Puede entregar una orden de venta'), ('orden.eliminar', 'Permite eliminar una orden de venta'), ('orden.actualizar', 'Permite actualizar una orden de venta'), ('orden.detalle', 'Permite ver el detalle de una orden de venta')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ArchivoOrdenDeVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='ordendeventa/adjuntos', verbose_name='Archivos Adjuntos')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.ordendeventa', verbose_name='Orden de venta')),
            ],
            options={
                'permissions': (('archivo.listar', 'Puede ver archivos adjuntos ov'), ('archivo.crear', 'Puede agregar un archivo a ov'), ('archivo.eliminar', 'Permite eliminar un archivo adjunto ov')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OrdenDeVentaCajaLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cerrada', models.BooleanField(default=True, verbose_name='Estado Caja')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.cajalote', verbose_name='Caja lote')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.ordendeventa', verbose_name='Orden de venta')),
            ],
            options={
                'verbose_name': 'Cajas OV',
                'verbose_name_plural': 'CAJAS OV',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OrdenDeVentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cliente', models.CharField(blank=True, default=None, max_length=255, verbose_name='Codigo Cliente')),
                ('cantidad', models.BigIntegerField(verbose_name='Cantidad')),
                ('cantidad_fc', models.BigIntegerField(default=0, verbose_name='Cantidad Facturada')),
                ('factura', models.CharField(blank=True, default='', max_length=255, verbose_name='N° Factura')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('descuento', models.FloatField(default=0, verbose_name='Descuento')),
                ('cantidad_en', models.BigIntegerField(default=0, verbose_name='Cantidad Entregada')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.ordendeventa', verbose_name='Orden de venta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='nucleo.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'Producto Orden de Venta',
                'verbose_name_plural': 'Productos Orden de Venta',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ListaPrecioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.listaprecio', verbose_name='Lista Asociada')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listaproductos', to='nucleo.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Producto Lista de Precios',
                'verbose_name_plural': 'Productos Listas de Precios',
                'ordering': ['producto__nombre'],
                'default_permissions': (),
                'unique_together': {('lista', 'producto')},
            },
        ),
    ]
