# Generated by Django 5.1.1 on 2024-09-20 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calidad', '0001_initial'),
        ('equipo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipoutensiliolimpieza',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo', verbose_name='Equipo'),
        ),
        migrations.AddField(
            model_name='grupoequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo'),
        ),
        migrations.AddField(
            model_name='grupoequipo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad.grupoequipos'),
        ),
        migrations.AddField(
            model_name='grupoutensilio',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad.grupoequipos'),
        ),
        migrations.AddField(
            model_name='registrolimpiezaequipo',
            name='encargado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encargado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='registrolimpiezaequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo', verbose_name='Equipo'),
        ),
        migrations.AddField(
            model_name='registrolimpiezaequipo',
            name='revisado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisado', to=settings.AUTH_USER_MODEL, verbose_name='Revisado'),
        ),
        migrations.AddField(
            model_name='registrolimpiezaequipohistorial',
            name='registrolimpiezequipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad.registrolimpiezaequipo', verbose_name='Registro Equipo'),
        ),
        migrations.AddField(
            model_name='registrolimpiezaequipo',
            name='utensilios',
            field=models.ManyToManyField(to='calidad.utensiliolimpieza', verbose_name='Utensilios'),
        ),
        migrations.AddField(
            model_name='grupoutensilio',
            name='utensilio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad.utensiliolimpieza'),
        ),
        migrations.AddField(
            model_name='equipoutensiliolimpieza',
            name='utensilio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad.utensiliolimpieza', verbose_name='Utensilio'),
        ),
        migrations.AlterUniqueTogether(
            name='equipoutensiliolimpieza',
            unique_together={('equipo', 'utensilio')},
        ),
    ]
