# Generated by Django 5.1.1 on 2024-09-20 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConjuntoEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre Conjunto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'conjunto',
                'verbose_name_plural': 'conjuntos',
                'ordering': ['-pk'],
                'permissions': (('conjuto.listar', 'Puede ver los conjuntos'), ('conjuto.detalle', 'Puede ver los detalles del conjunto'), ('conjuto.crear', 'Puede crear un conjunto'), ('conjuto.eliminar', 'Puede eliminar un conjunto'), ('conjuto.actualizar', 'Puede actualizar un conjunto')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('peso', models.BooleanField(default=False, verbose_name='Pedir Peso')),
                ('uc', models.BooleanField(default=False, verbose_name='Pedir Unidades Para Calidad')),
                ('uff', models.BooleanField(default=False, verbose_name='Pedir Unidades Fuera de Formato')),
                ('unc', models.BooleanField(default=False, verbose_name='Pedir Unidades No Consumibles')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EstadoConjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(verbose_name='Posicion')),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estado.conjuntoestado', verbose_name='Conjunto')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estado.estado', verbose_name='Estado')),
            ],
            options={
                'ordering': ['pos'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EstadoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estado.estado', verbose_name='Estado Asociado')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
