# Generated by Django 5.1.1 on 2024-09-20 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado', '0001_initial'),
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoinsumo',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.insumo', verbose_name='Insumo'),
        ),
        migrations.AddField(
            model_name='estadoproducto',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estado.estado', verbose_name='Estado Asociado'),
        ),
        migrations.AddField(
            model_name='estadoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.producto', verbose_name='Producto'),
        ),
        migrations.AlterUniqueTogether(
            name='estadoconjunto',
            unique_together={('conjunto', 'estado')},
        ),
        migrations.AlterUniqueTogether(
            name='estadoinsumo',
            unique_together={('estado', 'insumo')},
        ),
        migrations.AlterUniqueTogether(
            name='estadoproducto',
            unique_together={('estado', 'producto')},
        ),
    ]
