# Generated by Django 5.1.1 on 2024-09-20 15:35

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Columna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Parámetro')),
                ('tipo', models.CharField(choices=[('0', 'Entero'), ('1', 'Decimal'), ('2', 'Fecha'), ('3', 'Checkbox'), ('4', 'Texto')], default=1, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Parámetro',
                'verbose_name_plural': 'Parámetros',
                'permissions': (('columna.listar', 'Permite listar los parámetros'), ('columna.crear', 'Permite crear un parámetro'), ('columna.eliminar', 'Permite eliminar un parámetro'), ('columna.actualizar', 'Permite actualizar un parámetro')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(verbose_name='Orden')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre Etapa')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='HistoricalColumna',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Parámetro')),
                ('tipo', models.CharField(choices=[('0', 'Entero'), ('1', 'Decimal'), ('2', 'Fecha'), ('3', 'Checkbox'), ('4', 'Texto')], default=1, max_length=255)),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Parámetro',
                'verbose_name_plural': 'historical Parámetros',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInstruccion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('orden', models.IntegerField(verbose_name='Orden')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('puntocontrol', models.BooleanField(default=False, verbose_name='Punto de control')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('etapa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pauta.etapa', verbose_name='Etapa Asociada')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Instrucción',
                'verbose_name_plural': 'historical Instrucciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPauta',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre Pauta')),
                ('tipo', models.CharField(choices=[('PIP', 'PIP'), ('Linea', 'Linea')], default='PIP', max_length=255, verbose_name='Tipo de Pauta')),
                ('rendimiento', models.FloatField(blank=True, default='8.5', help_text='Cantidad de kilos o litros necesarios para producir 1 kilo de producto pip.', null=True, verbose_name='Rendimiento PIP')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Pauta de elaboración',
                'verbose_name_plural': 'historical Pautas de elaboración',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(verbose_name='Cantidad')),
                ('unidad', models.CharField(max_length=255)),
                ('opcional', models.BooleanField(default=False, verbose_name='Insumo Opcional')),
                ('original', models.BooleanField(default=True, verbose_name='Viene con la pauta por defecto')),
                ('lider', models.BooleanField(default=False, verbose_name='Ingrediente al 100%')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.insumo', verbose_name='Insumo')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Instruccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(verbose_name='Orden')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('puntocontrol', models.BooleanField(default=False, verbose_name='Punto de control')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pauta.etapa', verbose_name='Etapa Asociada')),
            ],
            options={
                'verbose_name': 'Instrucción',
                'verbose_name_plural': 'Instrucciones',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InstruccionColumna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('columna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pauta.columna', verbose_name='Columna asociada')),
                ('instruccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pauta.instruccion', verbose_name='Instrucción asociada')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Pauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre Pauta')),
                ('tipo', models.CharField(choices=[('PIP', 'PIP'), ('Linea', 'Linea')], default='PIP', max_length=255, verbose_name='Tipo de Pauta')),
                ('rendimiento', models.FloatField(blank=True, default='8.5', help_text='Cantidad de kilos o litros necesarios para producir 1 kilo de producto pip.', null=True, verbose_name='Rendimiento PIP')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('ingredientes', models.ManyToManyField(through='pauta.Ingrediente', to='nucleo.insumo', verbose_name='Ingredientes')),
            ],
            options={
                'verbose_name': 'Pauta de elaboración',
                'verbose_name_plural': 'Pautas de elaboración',
                'ordering': ['-id'],
                'permissions': (('listar', 'Permite listar las pautas de elaboración'), ('crear', 'Permite crear una pauta de elaboración'), ('eliminar', 'Permite eliminar una pauta de elaboración'), ('actualizar', 'Permite actualizar una pauta de elaboración'), ('detalle', 'Permite ver el detalle de una pauta')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='IngredienteProductoRestriccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbolo', models.IntegerField(choices=[(0, '<'), (1, '>'), (2, '='), (3, '<='), (4, '>=')], verbose_name='Operacion')),
                ('pmasa', models.FloatField(verbose_name='Porcentaje de masa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.producto', verbose_name='Grupo Producto')),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pauta.pauta', verbose_name='Pauta Asociada')),
            ],
            options={
                'verbose_name': 'Restriccion Ingrediente Producto',
                'verbose_name_plural': 'Restriccion Ingrediente Producto',
                'ordering': ['-id'],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='pauta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pauta.pauta', verbose_name='Pauta Asociada'),
        ),
        migrations.CreateModel(
            name='HistoricalIngrediente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cantidad', models.FloatField(verbose_name='Cantidad')),
                ('unidad', models.CharField(max_length=255)),
                ('opcional', models.BooleanField(default=False, verbose_name='Insumo Opcional')),
                ('original', models.BooleanField(default=True, verbose_name='Viene con la pauta por defecto')),
                ('lider', models.BooleanField(default=False, verbose_name='Ingrediente al 100%')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('insumo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nucleo.insumo', verbose_name='Insumo')),
                ('pauta', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pauta.pauta', verbose_name='Pauta Asociada')),
            ],
            options={
                'verbose_name': 'historical Ingrediente',
                'verbose_name_plural': 'historical Ingredientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEtapa',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('orden', models.IntegerField(verbose_name='Orden')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre Etapa')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pauta', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pauta.pauta', verbose_name='Pauta Asociada')),
            ],
            options={
                'verbose_name': 'historical Etapa',
                'verbose_name_plural': 'historical Etapas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='etapa',
            name='pauta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pauta.pauta', verbose_name='Pauta Asociada'),
        ),
        migrations.CreateModel(
            name='PautaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pauta.pauta', verbose_name='Pauta Asociada')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.producto', verbose_name='Grupo Producto')),
            ],
            options={
                'verbose_name': 'Pauta Producto',
                'verbose_name_plural': 'Pauta Producto',
                'ordering': ['-id'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InsumoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.insumo', verbose_name='Insumo')),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pauta.pauta', verbose_name='Pauta Asociada')),
            ],
            options={
                'verbose_name': 'Insumo Proceso',
                'verbose_name_plural': 'Insumo Proceso',
                'default_permissions': (),
                'unique_together': {('insumo', 'pauta')},
            },
        ),
        migrations.CreateModel(
            name='IngredienteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.producto', verbose_name='Grupo Producto')),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pauta.pauta', verbose_name='Pauta Asociada')),
            ],
            options={
                'verbose_name': 'Pauta Ingrediente Producto',
                'verbose_name_plural': 'Pauta Ingrediente Producto',
                'ordering': ['-id'],
                'default_permissions': (),
                'unique_together': {('pauta', 'producto')},
            },
        ),
    ]
