# Generated by Django 5.1.1 on 2024-09-20 15:35

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado', '0001_initial'),
        ('inventario', '0001_initial'),
        ('nucleo', '0001_initial'),
        ('pauta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Estado')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('peso', models.FloatField(blank=True, default=0, null=True, verbose_name='Peso')),
                ('unidadesNC', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unidades No Consumibles')),
                ('unidadesFF', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unidades Fuera de Formato')),
                ('unidadesC', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unidades Para Calidad')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('encargado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Encargado')),
                ('estadoGlobal', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estado.estado', verbose_name='Estado')),
                ('lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.bodega', verbose_name='Lugar')),
            ],
            options={
                'verbose_name': 'Estado de Lote',
                'verbose_name_plural': 'Estados de Lotes',
                'permissions': (('elote.eliminar', 'Permite eliminar un estado de lote'), ('elote.actualizar', 'Permite actualizar un estado de lote')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EstadoLoteInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(verbose_name='Cantidad')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.estadolote', verbose_name='Estado Lote')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.insumo', verbose_name='Insumo')),
            ],
            options={
                'verbose_name': 'Estado Lote Insumo',
                'verbose_name_plural': 'Estado Lote Insumos',
                'permissions': (('elote.eliminar', 'Permite eliminar un estado de lote'), ('elote.actualizar', 'Permite actualizar un estado de lote')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='HistoricalPautaProduccion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha de fabricación')),
                ('cantidad', models.FloatField(verbose_name='Cantidad a elaborar')),
                ('masa_final', models.FloatField(blank=True, null=True, verbose_name='Masa Final')),
                ('rendimiento', models.FloatField(default=8.5, verbose_name='Rendimiento')),
                ('estado', models.CharField(choices=[('En Elaboración', 'En Elaboración'), ('Segmentación', 'Segmentación'), ('Finalizada', 'Finalizada')], default='En Elaboración', max_length=255, verbose_name='Estado Pauta')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de actualización')),
                ('cdp', models.FloatField(default=0, verbose_name='Costo directo produccion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lugar', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.bodega', verbose_name='Lugar')),
                ('plantilla_pauta', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pauta.pauta', verbose_name='Pauta de elaboración a seguir')),
            ],
            options={
                'verbose_name': 'historical Pauta Producción',
                'verbose_name_plural': 'historical Pautas Producción',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255, verbose_name='Numero de Lote')),
                ('mostrar', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de fabricación')),
                ('cantidad', models.FloatField(verbose_name='Cantidad En Kilogramos o Unidades')),
                ('comentario', models.CharField(max_length=255, verbose_name='Comentarios')),
                ('cdp', models.FloatField(default=0, verbose_name='Costo Directo Produccion')),
                ('linea', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.linea', verbose_name='Linea de Producto')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.producto', verbose_name='Producto')),
                ('pva', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estado.conjuntoestado', verbose_name='Procesos de Valor Agregado')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-fecha'],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='estadolote',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produccion.lote', verbose_name='Lote'),
        ),
        migrations.CreateModel(
            name='CajaLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad por caja')),
                ('cantidad_a', models.IntegerField(default=0, verbose_name='Cantidad por caja')),
                ('caja', models.IntegerField(verbose_name='Caja')),
                ('recepcionado', models.BooleanField(default=None, null=True, verbose_name='Recepcionado')),
                ('estado', models.CharField(choices=[('Produccion', 'Produccion'), ('Transito', 'Transito'), ('Recepcionado', 'Recepcionado'), ('Abierto', 'Abierto'), ('Pickeado', 'Pickeado'), ('Cerrado', 'Cerrado'), ('Cliente', 'Cliente')], default='Produccion', max_length=20)),
                ('lugar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.bodega', verbose_name='Lugar')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produccion.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'caja lote',
                'verbose_name_plural': 'cajas lote',
                'default_permissions': (),
                'unique_together': {('lote', 'caja')},
            },
        ),
        migrations.CreateModel(
            name='PautaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha de fabricación')),
                ('cantidad', models.FloatField(verbose_name='Cantidad a elaborar')),
                ('masa_final', models.FloatField(blank=True, null=True, verbose_name='Masa Final')),
                ('rendimiento', models.FloatField(default=8.5, verbose_name='Rendimiento')),
                ('estado', models.CharField(choices=[('En Elaboración', 'En Elaboración'), ('Segmentación', 'Segmentación'), ('Finalizada', 'Finalizada')], default='En Elaboración', max_length=255, verbose_name='Estado Pauta')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('cdp', models.FloatField(default=0, verbose_name='Costo directo produccion')),
                ('lugar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.bodega', verbose_name='Lugar')),
                ('plantilla_pauta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pauta.pauta', verbose_name='Pauta de elaboración a seguir')),
            ],
            options={
                'verbose_name': 'Pauta Producción',
                'verbose_name_plural': 'Pautas Producción',
                'permissions': (('pauta.listar', 'Permite listar las pautas de producción'), ('pauta.crear', 'Permite crear una pauta de producción'), ('pauta.detalle', 'Permite ver el detalle de una pauta de producción'), ('pauta.eliminar', 'Permite eliminar una pauta de producción'), ('pauta.actualizar', 'Permite actualizar una pauta de producción')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ParticipanteProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('participante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Participante')),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.pautaproduccion', verbose_name='Pauta')),
            ],
            options={
                'verbose_name': 'Participante Elaboración',
                'verbose_name_plural': 'Participantes Elaboración',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='pauta_produccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produccion.pautaproduccion', verbose_name='Pauta Producción'),
        ),
        migrations.CreateModel(
            name='LineaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final', models.BooleanField(default=True, verbose_name='Resultado Final')),
                ('cantidad', models.FloatField(verbose_name='Cantidad Elaborada')),
                ('linea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.linea', verbose_name='Linea de Producto')),
                ('pva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estado.conjuntoestado', verbose_name='Procesos de valor agregado')),
                ('pauta_produccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produccion.pautaproduccion', verbose_name='Pauta Producción')),
            ],
            options={
                'verbose_name': 'Producto Producción',
                'verbose_name_plural': 'Productos Producción',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InsumoProcesoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0, verbose_name='Cantidad Producida')),
                ('cantidadu', models.FloatField(default=0, verbose_name='Cantidad Utilizada')),
                ('comentario', models.CharField(default='', max_length=255, verbose_name='Comentarios')),
                ('plantilla_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pauta.insumoproceso', verbose_name='Insumo Produccion')),
                ('pauta_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.pautaproduccion', verbose_name='Pauta Producción')),
            ],
            options={
                'verbose_name': 'Insumo Proceso Produccion',
                'verbose_name_plural': 'Insumos Proceso Producción',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InsumoPipUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(verbose_name='Cantidad Utilizada')),
                ('insumoproceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.insumoprocesoproduccion', verbose_name='Insumo proceso utilizado')),
                ('pauta_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.pautaproduccion', verbose_name='Pauta Producción')),
            ],
            options={
                'verbose_name': 'Insumo Proceso Produccion',
                'verbose_name_plural': 'Insumos Proceso Producción',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InstruccionProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
                ('plantilla_columna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pauta.columna', verbose_name='Columna')),
                ('plantilla_instruccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pauta.instruccion', verbose_name='Instrucción')),
                ('pauta_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.pautaproduccion', verbose_name='Pauta Producción')),
            ],
            options={
                'verbose_name': 'Instrucción Pauta Producción',
                'verbose_name_plural': 'Instrucciones Pautas Producción',
                'ordering': ['plantilla_columna__id'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='IngredienteProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(verbose_name='Cantidad Usada')),
                ('unidad', models.CharField(max_length=255, verbose_name='unidad')),
                ('plantilla_ingrediente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pauta.ingrediente', verbose_name='Ingrediente')),
                ('pauta_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.pautaproduccion', verbose_name='Pauta Producción')),
            ],
            options={
                'verbose_name': 'Ingrediente Pauta Producción',
                'verbose_name_plural': 'Ingredientes Pautas Producción',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CajaLotePautaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(verbose_name='Cantidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.cajalote', verbose_name='Caja Lote')),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.pautaproduccion', verbose_name='Pauta')),
            ],
            options={
                'verbose_name': 'Caja Pauta Produccion',
                'verbose_name_plural': 'Caja Pauta Produccion',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BultoPautaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(verbose_name='Cantidad')),
                ('bulto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.insumobulto', verbose_name='Bulto')),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.pautaproduccion', verbose_name='Pauta')),
            ],
            options={
                'verbose_name': 'Participante Elaboración',
                'verbose_name_plural': 'Participantes Elaboración',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProductoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final', models.BooleanField(default=True, verbose_name='Resultado Final')),
                ('cantidad', models.FloatField(verbose_name='Cantidad Elaborada')),
                ('pauta_produccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produccion.pautaproduccion', verbose_name='Pauta Producción')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Producto Producción',
                'verbose_name_plural': 'Productos Producción',
                'default_permissions': (),
            },
        ),
    ]
