# Generated by Django 5.1.1 on 2024-10-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpautaproduccion',
            name='estado',
            field=models.CharField(choices=[('En Elaboración', 'En Elaboración'), ('Segmentación', 'Segmentación'), ('Finalizada', 'Finalizada'), ('Corte', 'Corte'), ('Envasado', 'Envasado'), ('Producto Retenido', 'Producto Retenido')], default='En Elaboración', max_length=255, verbose_name='Estado Pauta'),
        ),
        migrations.AlterField(
            model_name='pautaproduccion',
            name='estado',
            field=models.CharField(choices=[('En Elaboración', 'En Elaboración'), ('Segmentación', 'Segmentación'), ('Finalizada', 'Finalizada'), ('Corte', 'Corte'), ('Envasado', 'Envasado'), ('Producto Retenido', 'Producto Retenido')], default='En Elaboración', max_length=255, verbose_name='Estado Pauta'),
        ),
    ]
