# Generated by Django 5.1.1 on 2024-10-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_alter_historicalpautaproduccion_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpautaproduccion',
            name='cdp',
            field=models.FloatField(default=0, verbose_name='Costo directo producción'),
        ),
        migrations.AlterField(
            model_name='pautaproduccion',
            name='cdp',
            field=models.FloatField(default=0, verbose_name='Costo directo producción'),
        ),
    ]
