# Generated by Django 5.1.1 on 2024-10-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_alter_historicalpautaproduccion_cdp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpautaproduccion',
            name='cdp',
            field=models.FloatField(default=0, verbose_name='Costo directo produccion'),
        ),
        migrations.AlterField(
            model_name='historicalpautaproduccion',
            name='estado',
            field=models.CharField(choices=[('En Elaboración', 'En Elaboración'), ('Segmentación', 'Segmentación'), ('Finalizada', 'Finalizada')], default='En Elaboración', max_length=255, verbose_name='Estado Pauta'),
        ),
        migrations.AlterField(
            model_name='pautaproduccion',
            name='cdp',
            field=models.FloatField(default=0, verbose_name='Costo directo produccion'),
        ),
        migrations.AlterField(
            model_name='pautaproduccion',
            name='estado',
            field=models.CharField(choices=[('En Elaboración', 'En Elaboración'), ('Segmentación', 'Segmentación'), ('Finalizada', 'Finalizada')], default='En Elaboración', max_length=255, verbose_name='Estado Pauta'),
        ),
    ]
