# Generated by Django 5.1.1 on 2024-11-11 11:33

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_alter_historicalpautaproduccion_cdp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalidadProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtro_instalado', models.CharField(max_length=255, verbose_name='Filtro Instalado')),
                ('filtro_integrado', models.CharField(max_length=255, verbose_name='Filtro Integrado')),
                ('inicio_envasado', models.CharField(max_length=255, verbose_name='Inicio Envasado')),
                ('fin_envasado', models.CharField(max_length=255, verbose_name='Fin Envasado')),
                ('unidades_botellas_lt', models.PositiveIntegerField(verbose_name='Unidades Botellas (lt)')),
                ('unidades_360gr', models.PositiveIntegerField(verbose_name='Unidades 360gr')),
                ('unidades_150gr', models.PositiveIntegerField(verbose_name='Unidades 150gr')),
                ('merma_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Merma (kg)')),
                ('ph', models.CharField(max_length=50, verbose_name='pH')),
                ('textura', models.CharField(max_length=50, verbose_name='Textura')),
                ('sabor', models.CharField(max_length=50, verbose_name='Sabor')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('olor', models.CharField(max_length=50, verbose_name='Olor')),
                ('aspecto', models.CharField(max_length=50, verbose_name='Aspecto')),
                ('elaboracion', models.CharField(max_length=255, verbose_name='Responsable Elaboración')),
                ('envasado', models.CharField(max_length=255, verbose_name='Responsable Envasado')),
                ('verificacion', models.CharField(max_length=255, verbose_name='Responsable Verificación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('pauta_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calidad_produccion', to='produccion.pautaproduccion', verbose_name='Pauta de Producción')),
            ],
            options={
                'verbose_name': 'Calidad de Producción',
                'verbose_name_plural': 'Calidades de Producción',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCalidadProduccion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('filtro_instalado', models.CharField(max_length=255, verbose_name='Filtro Instalado')),
                ('filtro_integrado', models.CharField(max_length=255, verbose_name='Filtro Integrado')),
                ('inicio_envasado', models.CharField(max_length=255, verbose_name='Inicio Envasado')),
                ('fin_envasado', models.CharField(max_length=255, verbose_name='Fin Envasado')),
                ('unidades_botellas_lt', models.PositiveIntegerField(verbose_name='Unidades Botellas (lt)')),
                ('unidades_360gr', models.PositiveIntegerField(verbose_name='Unidades 360gr')),
                ('unidades_150gr', models.PositiveIntegerField(verbose_name='Unidades 150gr')),
                ('merma_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Merma (kg)')),
                ('ph', models.CharField(max_length=50, verbose_name='pH')),
                ('textura', models.CharField(max_length=50, verbose_name='Textura')),
                ('sabor', models.CharField(max_length=50, verbose_name='Sabor')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('olor', models.CharField(max_length=50, verbose_name='Olor')),
                ('aspecto', models.CharField(max_length=50, verbose_name='Aspecto')),
                ('elaboracion', models.CharField(max_length=255, verbose_name='Responsable Elaboración')),
                ('envasado', models.CharField(max_length=255, verbose_name='Responsable Envasado')),
                ('verificacion', models.CharField(max_length=255, verbose_name='Responsable Verificación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pauta_produccion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='produccion.pautaproduccion', verbose_name='Pauta de Producción')),
            ],
            options={
                'verbose_name': 'historical Calidad de Producción',
                'verbose_name_plural': 'historical Calidades de Producción',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
