# Generated by Django 5.1.1 on 2024-11-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0005_calidadproduccion_historicalcalidadproduccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='calidadproduccion',
            name='estado_aprobacion',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Desaprobado', 'Desaprobado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=11, verbose_name='Estado de Aprobación'),
        ),
        migrations.AddField(
            model_name='historicalcalidadproduccion',
            name='estado_aprobacion',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Desaprobado', 'Desaprobado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=11, verbose_name='Estado de Aprobación'),
        ),
    ]
