# Generated by Django 5.1.1 on 2024-11-11 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0007_alter_calidadproduccion_estado_aprobacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calidadproduccion',
            name='instrucciones',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produccion.instruccionproduccion', verbose_name='instrucciones'),
        ),
        migrations.AddField(
            model_name='historicalcalidadproduccion',
            name='instrucciones',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='produccion.instruccionproduccion', verbose_name='instrucciones'),
        ),
    ]
