# Generated by Django 5.1.1 on 2024-11-11 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0008_calidadproduccion_instrucciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calidadproduccion',
            name='instrucciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produccion.instruccionproduccion', verbose_name='instrucciones'),
        ),
        migrations.AlterField(
            model_name='historicalcalidadproduccion',
            name='instrucciones',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='produccion.instruccionproduccion', verbose_name='instrucciones'),
        ),
    ]
