# Generated by Django 5.1.1 on 2024-09-20 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_initial'),
        ('produccion', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(verbose_name='Fecha de envio')),
                ('fecha_recepcion', models.DateTimeField(null=True, verbose_name='Fecha de recepción')),
                ('estado', models.BooleanField(default=0, verbose_name='Recepcionado')),
                ('medio_transporte', models.CharField(max_length=255, verbose_name='Medio de Transporte')),
                ('numero_documento', models.CharField(max_length=255, verbose_name='Número de documento')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('encargado_envio', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encargado_envio', to=settings.AUTH_USER_MODEL, verbose_name='Encargado Envio')),
                ('encargado_recepcion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Encargado Recepción')),
                ('lugar_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='inventario.bodega', verbose_name='Lugar de Destino')),
                ('lugar_o', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='inventario.bodega', verbose_name='Lugar de Origen')),
            ],
            options={
                'verbose_name': 'envio',
                'verbose_name_plural': 'envios',
                'ordering': ['-pk'],
                'permissions': (('envio.listar', 'Puede ver los envios'), ('envio.detalle', 'Puede ver los detalles del envio'), ('envio.crear', 'Puede crear un envio'), ('envio.etiquetas', 'Puede ver las etiquetas del envio'), ('envio.eliminar', 'Puede eliminar una envio'), ('envio.actualizar', 'Puede actualizar un envio')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InsumoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recepcionado', models.BooleanField(default=None, null=True, verbose_name='Recepcionado')),
                ('envio', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistica.envio')),
                ('insumobulto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.insumobulto')),
            ],
            options={
                'verbose_name': 'envio insumo bulto',
                'verbose_name_plural': 'envios insumo bulto',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LoteEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recepcionado', models.BooleanField(default=None, null=True, verbose_name='Recepcionado')),
                ('cajalote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.cajalote', verbose_name='Caja Lote')),
                ('envio', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistica.envio')),
            ],
            options={
                'verbose_name': 'envio lote',
                'verbose_name_plural': 'envios lote',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Pallet')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('envio', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistica.envio', verbose_name='Envio')),
                ('lugar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.bodega', verbose_name='Lugar')),
            ],
            options={
                'verbose_name': 'pallet',
                'verbose_name_plural': 'pallets',
                'permissions': (('pallet.listar', 'Puede ver los pallets'), ('pallet.detalle', 'Puede ver el codigo de barra del pallet'), ('pallet.crear', 'Puede agregar un pallet'), ('pallet.eliminar', 'Puede eliminar un pallet'), ('pallet.actualizar', 'Puede actualizar un pallet')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RegistroPallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False, verbose_name='completado')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.envio', verbose_name='envio')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.pallet', verbose_name='pallet')),
            ],
            options={
                'verbose_name': 'registro pallet',
                'verbose_name_plural': 'registro pallets',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la ruta')),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=255, verbose_name='Estado')),
                ('patente', models.CharField(blank=True, default='', max_length=10, verbose_name='Patente del Vehiculo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Transportista')),
            ],
            options={
                'verbose_name': 'ruta',
                'verbose_name_plural': 'rutas',
                'ordering': ['-pk'],
                'permissions': (('rutas.listar', 'Puede ver las rutas'), ('rutas.misrutas', 'Puede ver las rutas asignadas'), ('rutas.detalle', 'Puede ver el detalle de la ruta'), ('rutas.crear', 'Puede crear una ruta'), ('rutas.cerrar', 'Puede cerrar una ruta'), ('rutas.eliminar', 'Puede eliminar una ruta'), ('rutas.actualizar', 'Puede actualizar una ruta')),
                'default_permissions': (),
                'unique_together': {('nombre', 'persona')},
            },
        ),
        migrations.CreateModel(
            name='RutaOv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.ordendeventa', verbose_name='Orden de Venta')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.ruta', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'rutas orden deventa',
                'verbose_name_plural': 'rutas orden deventa',
                'ordering': ['-pk'],
                'default_permissions': (),
            },
        ),
    ]
