# Generated by Django 5.1.1 on 2024-09-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcuerdoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.FloatField(verbose_name='Porcentaje')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Acuerdo Comercial',
                'verbose_name_plural': 'Acuerdos Comerciales',
                'ordering': ['-created'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('', '-- Seleccione --'), ('HORECA', 'Hotel - Restaurant - Casino'), ('Retail', 'Retail'), ('Venta Web,', 'Venta Web'), ('Persona Natural', 'Persona Natural')], max_length=255, verbose_name='tipo de cliente')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre comercial')),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='razón social')),
                ('rut', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rut Cliente')),
                ('giro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Giro Cliente')),
                ('pago', models.CharField(blank=True, choices=[('', '-- Seleccione --'), ('Contado', 'Contado'), ('Credito 15 días', 'Credito 15 días'), ('Credito 30 días', 'Credito 30 días'), ('Credito 60 días', 'Credito 60 días')], max_length=255, null=True, verbose_name='Forma de Pago')),
                ('telefono', models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono Cliente')),
                ('region', models.CharField(blank=True, choices=[('Metropolitana', 'Región Metropolitana'), ('Tarapacá', 'Tarapacá'), ('Antofagasta', 'Antofagasta'), ('Atacama', 'Atacama'), ('Coquimbo', 'Coquimbo'), ('Valparaiso', 'Valparaíso'), ('OHiggins', 'Región del Libertador Gral. Bernardo OHiggins'), ('Maule', 'Región del Maule'), ('Biobío', 'Región del Biobío'), ('Araucanía', 'Región de la Araucanía'), ('Los Ríos', 'Región de Los Ríos'), ('Los Lagos', 'Región de Los Lagos'), ('Aysén', 'Región Aisén del Gral. Carlos Ibáñez del Campo'), ('Antártica', 'Región de Magallanes y de la Antártica Chilena'), ('Arica y Parinacota', 'Arica y Parinacota'), ('Ñuble', 'Región de Ñuble')], max_length=255, null=True, verbose_name='Región')),
                ('comuna', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comuna')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('contacto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Contacto')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico')),
                ('celular', models.CharField(blank=True, max_length=255, null=True, verbose_name='Celular Contacto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['-created'],
                'permissions': (('cliente.listar', 'Puede ver el listado de los clientes'), ('cliente.crear', 'Puede crear un cliente'), ('cliente.eliminar', 'Permite eliminar un cliente'), ('cliente.actualizar', 'Permite actualizar un cliente'), ('cliente.detalle', 'Permite ver el detalle de un cliente')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ClienteLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=255, verbose_name='Nombre del local')),
                ('telefono', models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono')),
                ('region', models.CharField(blank=True, choices=[('Metropolitana', 'Región Metropolitana'), ('Tarapacá', 'Tarapacá'), ('Antofagasta', 'Antofagasta'), ('Atacama', 'Atacama'), ('Coquimbo', 'Coquimbo'), ('Valparaiso', 'Valparaíso'), ('OHiggins', 'Región del Libertador Gral. Bernardo OHiggins'), ('Maule', 'Región del Maule'), ('Biobío', 'Región del Biobío'), ('Araucanía', 'Región de la Araucanía'), ('Los Ríos', 'Región de Los Ríos'), ('Los Lagos', 'Región de Los Lagos'), ('Aysén', 'Región Aisén del Gral. Carlos Ibáñez del Campo'), ('Antártica', 'Región de Magallanes y de la Antártica Chilena'), ('Arica y Parinacota', 'Arica y Parinacota'), ('Ñuble', 'Región de Ñuble')], max_length=255, null=True, verbose_name='Región')),
                ('comuna', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comuna')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('contacto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Contacto')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico')),
                ('celular', models.CharField(blank=True, max_length=255, null=True, verbose_name='Celular Contacto')),
                ('id_comercio_electronico', models.CharField(blank=True, max_length=255, null=True, verbose_name='Identificador Comercio Electrónico')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'local',
                'verbose_name_plural': 'locales',
                'ordering': ['-created'],
                'permissions': (('local.listar', 'Puede ver el listado de los locales'), ('local.crear', 'Puede crear un local'), ('local.eliminar', 'Permite eliminar un local'), ('local.actualizar', 'Permite actualizar un local'), ('local.detalle', 'Permite ver el detalle de un local')),
                'default_permissions': (),
            },
        ),
    ]
