# Generated by Django 5.1.1 on 2024-09-20 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('nucleo', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuerdocomercial',
            name='rama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.rama', verbose_name='Rama'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='listap',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.listaprecio', verbose_name='Lista de Precios'),
        ),
        migrations.AddField(
            model_name='acuerdocomercial',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='clientelocal',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterUniqueTogether(
            name='acuerdocomercial',
            unique_together={('cliente', 'rama')},
        ),
    ]
