# Generated by Django 5.1.1 on 2024-09-20 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_nombre', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('empresa_rut', models.CharField(max_length=50, unique=True, verbose_name='Rut Empresa')),
                ('empresa_giro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Giro Empresa')),
                ('empresa_region', models.CharField(blank=True, choices=[('Metropolitana', 'Región Metropolitana'), ('Tarapacá', 'Tarapacá'), ('Antofagasta', 'Antofagasta'), ('Atacama', 'Atacama'), ('Coquimbo', 'Coquimbo'), ('Valparaiso', 'Valparaíso'), ('OHiggins', 'Región del Libertador Gral. Bernardo OHiggins'), ('Maule', 'Región del Maule'), ('Biobío', 'Región del Biobío'), ('Araucanía', 'Región de la Araucanía'), ('Los Ríos', 'Región de Los Ríos'), ('Los Lagos', 'Región de Los Lagos'), ('Aysén', 'Región Aisén del Gral. Carlos Ibáñez del Campo'), ('Antártica', 'Región de Magallanes y de la Antártica Chilena'), ('Arica y Parinacota', 'Arica y Parinacota'), ('Ñuble', 'Región de Ñuble')], max_length=255, null=True, verbose_name='Región')),
                ('empresa_comuna', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comuna')),
                ('empresa_direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Empresa')),
                ('ventas_nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Contacto Comercial')),
                ('ventas_email', models.EmailField(max_length=255, verbose_name='Correo Electrónico Contacto Comercial')),
                ('ventas_celular', models.CharField(blank=True, max_length=255, null=True, verbose_name='Celular Contacto Comercial')),
                ('cuenta_corriente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de cuenta corriente')),
                ('banco', models.CharField(blank=True, choices=[('BANCO_ESTADO', 'BANCOESTADO'), ('COOPEUCH', 'COOPEUCH'), ('BANCO_BBVA', 'BANCO BBVA'), ('BANCO_CONSORCIO', 'BANCO CONSORCIO'), ('BANCO_RIPLEY', 'BANCO RIPLEY'), ('BANCO_FALABELLA', 'BANCO FALABELLA'), ('BANCO_SECURITY', 'BANCO SECURITY'), ('BANCO_ITAU', 'BANCO ITAU'), ('BANCO_SANTANDER', 'BANCO SANTANDER'), ('HSBC_BANK_CHILE', 'HSBC BANK CHILE'), ('BICE', 'BICE'), ('CORP_BANCA', 'CORPBANCA'), ('BANCO_DE_CREDITO_E_INVERSIONES', 'BANCO DE CREDITO E INVERSIONES'), ('SCOTIABANK_DESARROLLO', 'SCOTIABANK CHILE'), ('BANCO_INTERNACIONAL', 'BANCO INTERNACIONAL'), ('BANCO_DE_CHILE', 'BANCO DE CHILE')], max_length=255, null=True, verbose_name='Banco')),
                ('transferencia_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico Transferencias')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'proovedor',
                'verbose_name_plural': 'proveedores',
                'ordering': ['-created'],
                'permissions': (('listar', 'Puede ver el listado de los proveedores'), ('crear', 'Puede crear un proveedor'), ('eliminar', 'Permite eliminar un proveedor'), ('actualizar', 'Permite actualizar un proveedor'), ('detalle', 'Permite ver el detalle de un proveedor')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProveedorInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_insumo', models.CharField(max_length=255, verbose_name='Nombre Insumo en ficha tecnica proveedor')),
                ('formato', models.FloatField(verbose_name='Formato De Compra')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('lead', models.IntegerField(default=15, verbose_name='Lead Time')),
                ('mostrar', models.BooleanField(default=True, verbose_name='Mostrar')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.insumo', verbose_name='insumo')),
                ('moneda', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.moneda', verbose_name='Vincular a este precio')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor', verbose_name='proveedor')),
            ],
            options={
                'verbose_name': 'Asociación Proveedor Insumo',
                'verbose_name_plural': 'Asociaciones Proveedores Insumos',
                'ordering': ['-created'],
                'permissions': (('insumo.listar', 'Puede ver el listado de las asociaciones'), ('insumo.crear', 'Puede crear una asociación'), ('insumo.actualizar', 'Puede actualizar una asociación'), ('insumo.eliminar', 'Puede eliminar una asociación')),
                'default_permissions': (),
            },
        ),
    ]
