# Generated by Django 5.1.1 on 2024-10-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='empresa_rut',
            field=models.CharField(max_length=50, verbose_name='Rut Empresa'),
        ),
        migrations.AlterField(
            model_name='proveedorinsumo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
    ]
